/**
 * @file mutation-types
 * @author HUI
 * @date 2017/7/20
 */
//site
export const FETCHSITESTATESUCCESS = "FETCHSITESTATESUCCESS";//取网站状态成功
export const FETCHSITEINFOSUCCESS = "FETCHSITEINFOSUCCESS"; //取网站信息成功

//Node
export const FETCHNODEINFOSUCCESS = "FETCHNODEINFOSUCCESS"; //取节点信息成功
export const FETCHNODEALLSUCCESS = "FETCHNODEALLSUCCESS"; //取所有节点成功

//Topic
export const FETCHTOPICSLATESTSUCCESS = "FETCHTOPICSLATESTSUCCESS"; //取最新主题成功
export const FETCHTOPICSHOTSUCCESS = "FETCHTOPICSHOTSUCCESS"; //取最热主题成功
export const FETCHTOPICSINFOSUCCESS = "FETCHTOPICSINFOSUCCESS"; //取主题信息成功

//Replies
export const FETCHREPLIESSUCCESS = "FETCHREPLIESSUCCESS"; //取主题回复成功

//Members
export const FETCHMEMBERINFOSUCCESS = "FETCHMEMBERINFOSUCCESS"; //取用户信息成功

